### PR TITLE
np version check fix

### PR DESCRIPTION
**Pull request by JangidBhavnesh**
The load_library(libname) function at https://github.com/MatthewRHermes/mrh/blob/master/lib/helper.py has a weird way of checking the np version. Like, if condition is becoming true if np version is 1.21.6.

In this PR, I am adding a fix to make it consistent so that this condition becomes true for the np version less than or equal to the 1.6. 

Thank You

### CODE REVIEW

**Comment by MatthewRHermes** [comment]
I don't think that quite works the way you want it to:
```
>>> a = tuple (map (int, '1.6'.split ('.')))
>>> b = tuple (map (int, '1.6.1'.split ('.')))
>>> b<=a
False
>>> '1.6' in '1.6.1'
True
```
Should it just check that the first two elements of the tuple are exactly '1', '6'?

**Comment by MatthewRHermes** [comment]
Anyway this is so old that the corresponding code no longer exists in PySCF itself, probably because the maintainers gave up on supporting numpy 1.6

**Comment by JangidBhavnesh** [comment]
**Current code fails for numpy version 1.21.6

>>> '1.6' in '1.21.6'
True

I tried to overcome that by using above function. But clearly that doesn't seem the correct way.**

With new commit, I think it will be overcome for any np version less than 1.6.2

>>> version_tuple('1.6.0') <= version_tuple('1.6.2')
True
>>> version_tuple('1.5.0') <= version_tuple('1.6.2')
True
>>> version_tuple('1.11.0') <= version_tuple('1.6.2')
False
>>> version_tuple('1.3.0') <= version_tuple('1.6.2')
True
>>> version_tuple('1.1.0') <= version_tuple('1.6.2')
True
>>> version_tuple('1.6') <= version_tuple('1.6.2')
True

I know this isn't the best way but it is solving the problem.  If you have any other suggestion then please let me know.

Thank you

**Comment by MatthewRHermes** [comment]
I think it was specifically 1.6 that had the bug, in fact at one point a PySCF warning recommended you downgrade if you had 1.6. Should it just check that the first two elements of the tuple are exactly '1', '6'?

**Comment by JangidBhavnesh** [comment]
So, Instead of less than 1.6 version, I will make it for 1.6.x only.
 
>>> version_tuple('1.1.1') == version_tuple('1.6.2')
False
>>> version_tuple('1.1.2') == version_tuple('1.6.2')
False
>>> version_tuple('1.1') == version_tuple('1.6.2')
False
>>> version_tuple('1.6') == version_tuple('1.6.2')
True
>>> version_tuple('1.7') == version_tuple('1.6.2')
False

How does this look?

**Comment by MatthewRHermes** [comment]
But what about 1.6.1, or 1.6.0? Again, **Should it just check that the first two elements of the tuple are exactly '1', '6'?**

**Comment by MatthewRHermes** [comment]
I don't think it's the clearest thing in the world when you define something called "version_tuple" that throws away part of the version tuple. Can you just index on the equality, rather than the function definition? It's less efficient but it's clearer to read.

**Comment by MatthewRHermes** [comment]
P.S. ignore my deleted comment, I wasn't looking closely enough before I sent that.

**Comment by MatthewRHermes** [comment]
Whatever I'll just do it myself

**Pull request merged**
