### PR TITLE
LASSI kernel updates

### PR DESCRIPTION
**Pull request by JangidBhavnesh**
As suggested in issue #27, I have added those variables to method class.

### CODE REVIEW

**Comment by JangidBhavnesh** [comment]
I have included the changes made in lassi.py, i.e. yesterday's commit d8bffddea013735e3da6d4de4d95e1de2eb5598e.

**Comment by MatthewRHermes** [comment]
If you pull and merge from my MatthewRHermes:dev into your local master branch, then the conflict that appears here will appear for you locally, and you will be able to resolve it in the obvious way. Then push that to JangidBhavnesh:master and it'll appear here as a pull request with no conflicts.

**Comment by MatthewRHermes** [comment]
Can "lassi/lassi_dms.py", "lassi/lassi_op_o0.py", and "lassi/lassi_op_o1.py" become "lassi/dms.py", "lassi/op_o0.py", and "lassi/op_o1.py"?

**Comment by JangidBhavnesh** [comment]
These file are being renamed and required changes has been made.

**Pull request merged**
