### PR TITLE
CMS-PDFT permanent and transition dipole moments

### PR DESCRIPTION
**Pull request by aolykhin**

### CODE REVIEW

**Comment by MatthewRHermes** [comment]
Could you get rid of my_pyscf/mcpdft/sipdft.py? I think it's just an old version of /mspdft.py, right?

I'm going to have to insist on leaving that SAMCSCF warning in the code until there are unit tests for it.

**Comment by MatthewRHermes** [comment]
Also, what's going on with that last commit? The message says you "added" unittests but the changelog says you deleted them? Could you double-check this?

**Comment by aolykhin** [comment]
Oh, I forgot to add untracked tests to the last commit. Here they are together with sa-pdft test. 
The old version, file my_pyscf/mcpdft/sipdft.py, has been removed.

**Comment by MatthewRHermes** [comment]
Is there a sign problem in test_cmspdft_tdm.py?

```
======================================================================
FAIL: test_furan_cation_cms2_tblyp_sto3g (__main__.KnownValues) (k=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cmspdft_tdm.py", line 79, in test_furan_cation_cms2_tblyp_sto3g
    self.assertAlmostEqual(tdmt,tdmr)
AssertionError: 0.3424476739104106 != -0.342447674 within 7 places (0.6848953479104105 difference)

======================================================================
FAIL: test_furan_cation_cms2_tblyp_sto3g (__main__.KnownValues) (k=2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cmspdft_tdm.py", line 79, in test_furan_cation_cms2_tblyp_sto3g
    self.assertAlmostEqual(tdmt,tdmr)
AssertionError: -0.1840490780169613 != 0.184049078 within 7 places (0.3680981560169613 difference)

======================================================================
FAIL: test_furan_cms3_tpbe_sto3g (__main__.KnownValues) (k=0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cmspdft_tdm.py", line 61, in test_furan_cms3_tpbe_sto3g
    self.assertAlmostEqual(tdmt,tdmr)
AssertionError: 0.20466538309053428 != -0.204665383 within 7 places (0.4093307660905343 difference)

======================================================================
FAIL: test_furan_cms3_tpbe_sto3g (__main__.KnownValues) (k=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cmspdft_tdm.py", line 61, in test_furan_cms3_tpbe_sto3g
    self.assertAlmostEqual(tdmt,tdmr)
AssertionError: 0.6833553181157647 != -0.683355318 within 7 places (1.3667106361157648 difference)
```

**Comment by aolykhin** [comment]
I couldn't reproduce this error, however, I see how this could happen. The sign of TDM has no physical meaning and it is rather a convention we choose. If a CI vector gets rotated by 180 deg turning |0> into -|0> then corresponding TDM <0|mu|1> would turn into -<0|mu|1>. In the case of CMS-PDFT, Lagrange multipliers may have opposite signs because two degenerate solutions exist. This degeneracy would lead to the reflection of the CMS-PDFT TDM. I have changed the unit test to check for a possible inversion of TDM

**Pull request merged**
