### PR TITLE
Initial commit of gpulib package

### PR DESCRIPTION
**Pull request by cjknight**
Bulk of libGPU code modifications contained in new mrh/gpu directory. There is a top-level README with initial documentation: mrh/gpu/README.md.

Couple libGPU examples in new examples/gpu directory.

Small edits to few files in mrh/my_pyscf/mcscf to add gpu hook. Some of these will be removed soon.

Should compile and give correct results for the 1, 2, 4, 8 fragments tested in polymer examples. Currently debugging numerical issue triggering many more iterations than expected. :(

### CODE REVIEW

**Comment by MatthewRHermes** [comment]
Can you fix the conflicts?

```
my_pyscf/mcscf/lasscf_async.py -> my_pyscf/mcscf/lasscf_async/lasscf_async.py
my_pyscf/mcscf/lasscf_async_crunch.py -> my_pyscf/mcscf/lasscf_async/crunch.py
```

**Comment by cjknight** [comment]
oops... done

**Comment by cjknight** [comment]
I believe I have fixed numerical issue in host backend: get_jk() call from impurity.kernel() uses different indexing scheme for vk (no idea why, but still testing fix to be sure).

I will clean up this fix and create a stubs libgpu module over next few days.

**Comment by MatthewRHermes** [comment]
In what way is the indexing scheme of get_jk inside impurity.kernel different? Is this related to the tuples that are passed [here](https://github.com/pyscf/pyscf/blob/master/pyscf/mcscf/mc1step.py#L98C13-L98C13) and [here](https://github.com/pyscf/pyscf/blob/master/pyscf/mcscf/mc1step.py#L1027C11-L1027C11) in the PySCF code?

**Comment by cjknight** [comment]
Working on things. Please don't merge until all-clear given.

**Comment by cjknight** [comment]
I'm still debugging a small 0.025319 energy difference that appears in the polymer_async example with nfrags=8. Identical energies and iteration counts are observed for nfrags=1, 2, and 4. 

Knowing who will be testing this code, I'm ok with merging this PR to let others start gearing up for their own testing while I continue debugging this.

**Pull request merged**
